name: NBTChangeCommands
version: '${project.version}'
main: org.s1queence.plugin.NBTChangeCommands
api-version: '1.18'
depend: [S1queenceLib]
commands:
  nbtchangecommands:
    usage: /nbtcc reload
    permission: nbtcc.perms.reload
    aliases:
      - nbtcc
  rename:
    usage: /rename <name>
  sign:
    usage:  /sign || /sign <text>
  resign:
    usage: /resign || /resign all
    permission: nbtcc.perms.resign